# models/alert.py
#
# Alert — generated when a suspicious pattern is detected in the logs.
# Each alert corresponds to one detected attack signature.

from pydantic import BaseModel, Field
from typing import Optional, List


class Alert(BaseModel):
    """
    A security alert generated by the pattern matcher.
    """
    alert_id:        str            # e.g. "A001"
    timestamp:       str            # When the alert was generated
    source_ip:       str            # Origin of the suspicious activity
    destination_ip:  str            # Target of the suspicious activity
    attack_type:     str            # e.g. "BRUTE_FORCE", "MALWARE_ATTACK"
    severity:        str            # LOW / MEDIUM / HIGH / CRITICAL
    description:     str            # Human-readable description
    related_log_ids: List[str]      # Which log entries triggered this alert
    signature_id:    str            # Which signature matched (e.g. "SIG001")
    kill_chain_stage: str           # Which stage of the kill chain this maps to


class AlertInDB(Alert):
    """Alert as stored in MongoDB."""
    id: Optional[str] = Field(default=None, alias="_id")

    class Config:
        populate_by_name = True


# Severity order used by the Priority Queue (higher number = higher priority)
SEVERITY_ORDER = {
    "CRITICAL": 4,
    "HIGH":     3,
    "MEDIUM":   2,
    "LOW":      1
}
